// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgPGc1PwBqEojqrcfLMqqeS-TMzReINY',
    appId: '1:119609407897:web:0db64ea12f4f508827bb08',
    messagingSenderId: '119609407897',
    projectId: 'iaproject-ca2fc',
    authDomain: 'iaproject-ca2fc.firebaseapp.com',
    databaseURL: 'https://iaproject-ca2fc-default-rtdb.firebaseio.com',
    storageBucket: 'iaproject-ca2fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4B-JQMxQeDg4iWLclh6rUmMxgvmXjlLE',
    appId: '1:119609407897:android:d81eaf1baf9d3e1427bb08',
    messagingSenderId: '119609407897',
    projectId: 'iaproject-ca2fc',
    databaseURL: 'https://iaproject-ca2fc-default-rtdb.firebaseio.com',
    storageBucket: 'iaproject-ca2fc.appspot.com',
  );
}
